= dng(1)
Lawrence Thorpe
:doctype: manpage
:manmanual: DNG
:mansource: DNG
:man-linkstyle: pass:[blue R < >]

== Name

dng - wrapper around Adobe DNG Converter via wine to provide POSIX command line parsing

== Synopsis

*dng* [_OPTION_]... _FILE_...

== Options

*-c*::
    Output compressed DNG files (default).

*-u*::
    Output uncompressed DNG files.

*-l*::
    Output linear DNG files.

*-e*::
    Embed original raw file inside DNG files.

*-p0*::
    Set JPEG preview size to none.

*-p1*::
    Set JPEG preview size to medium size (default).

*-p2*::
    Set JPEG preview size to full size.

*-fl*::
    Embed fast load data.

*-lossy*::
    Specify lossy compression. Defaults to preserve pixel count.
    Specify a long-side pixels or megapixels limit with optional *-side* or *-count* options defined below.
    Valid for Camera Raw compatibility 6.6 or later.

*-side*::
    Specify a long-side pixels value from 32 to 65000 pixels.

*-count*::
    Specify a megapixels limit of 1024 (1MB) or greater.

*-cr2.4*::
    Set Camera Raw compatibility to 2.4 and later

*-cr4.1*::
    Set Camera Raw compatibility to 4.1 and later

*-cr4.6*::
    Set Camera Raw compatibility to 4.6 and later

*-cr5.4*::
    Set Camera Raw compatibility to 5.4 and later

*-cr6.6*::
    Set Camera Raw compatibility to 6.6 and later

*-cr7.1*::
    Set Camera Raw compatibility to 7.1 and later (default)

*-dng1.1*::
    Set DNG backward version to 1.1

*-dng1.3*::
    Set DNG backward version to 1.3

*-dng1.4*::
    Set DNG backward version to 1.4 (default)

*-x*::
    Extract original embedded raw file(s) from source file argument(s).
    Overrides options above.

*-d*=_OUT_FILE_::
    Output converted or extracted files to the specified directory.
    Default to the parent directory of the input file.
    In the case of multiple input files, it defaults to the parent directory of each file.

*-o*=_OUT_FILE_::
    Specify the name of the output DNG file.
    Default is the name of the input file with the extension changed to "`.dng`".
    When converting multiple files with a single command, output files will use this as a base name and will be numbered sequentially.
    Ignored when using *-x* option.

== Resources

*Project web site:* https://github.com/thorpelawrence/dng-converter.sh

*Original documentation:* https://web.archive.org/web/20220714201445/https://helpx.adobe.com/content/dam/help/en/photoshop/pdf/dng_commandline.pdf

== Copying

Copyright (C) 2022 {author}. +
Free use of this software is granted under the terms of the MIT License.
